// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only used by `prisma migrate dev` / `migrate diff --from-migrations`
    // (replays migrations into a throwaway DB to compute drift). Unset at
    // runtime and in production; set in CI + local migration work.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
